### PR TITLE
Fixed: Broken links with anchors from API docs to guides

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Task/bugfix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests) and
[how to create tests](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## What changes did you make?

Fixed few links from API docs to guides.

#1700

### CODE REVIEW

**Comment by jacekbogdanski** [comment]
Changes looks good but there are more invalid links in our docs:

`#!/guide/dev_captionedimage`

https://github.com/ckeditor/ckeditor-dev/blob/t/1700/plugins/image2/plugin.js#L1607
https://github.com/ckeditor/ckeditor-dev/blob/t/1700/plugins/image2/plugin.js#L1622
https://github.com/ckeditor/ckeditor-dev/blob/t/1700/plugins/image2/plugin.js#L1635
https://github.com/ckeditor/ckeditor-dev/blob/t/1700/plugins/image2/plugin.js#L1695
https://github.com/ckeditor/ckeditor-dev/blob/t/1700/plugins/image2/plugin.js#L1708

It's not an link to guides but I think it could be good idea to fix it with this PR:
https://github.com/ckeditor/ckeditor-dev/blob/t/1700/plugins/clipboard/plugin.js#L1671

**Comment by engineering-this** [comment]
I fixed `@link` which didn't refer to any of our docs, to regular markdown style link `[text](url)`. When building docs umberto doesn't print any warnings, so it should be fine now.

**Comment by jacekbogdanski** [comment]
After 4.9.0 release Umberto complains about broken links for 4.10.0 release. I think it's not an issue because it's not published yet and we can still have some missing docs but probably we should merge this branch into `master` not `major`. Nevertheless there are new broken link warnings for the `master` branch. 

@mlewand could you refer to the question about target branch for this PR? 

@engineering-this please rebase your PR branch to the latest `master/major` (depends on @mlewand response) and verify broken link warnings from Umberto.

Broken links for the `master` branch: 

`
Warning: Possible broken link {@linkapi CKEDITOR.config.corePlugins CKEDITOR.config.corePlugins} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.skins CKEDITOR.skins} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.themes CKEDITOR.themes} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.editor#getMode CKEDITOR.editor#getMode} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.config.editingBlock CKEDITOR.config.editingBlock} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.focusManager#forceBlur CKEDITOR.focusManager#forceBlur} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.config.toolbar_Basic CKEDITOR.config.toolbar_Basic} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.config.toolbar_Full CKEDITOR.config.toolbar_Full} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.editor#addCss CKEDITOR.editor#addCss} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.editor#getThemeSpace CKEDITOR.editor#getThemeSpace} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.editor#space CKEDITOR.editor#space} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.editor#themeSpace CKEDITOR.editor#themeSpace} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.editor#uiSpace CKEDITOR.editor#uiSpace} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.replaceByClassEnabled CKEDITOR.replaceByClassEnabled} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.dtd.s-captionBlock CKEDITOR.dtd.$captionBlock} in ckeditor4/4.9.0/guide/dev/api_changes/README.md
Warning: Possible broken link {@linkapi CKEDITOR.parent CKEDITOR.parent} in ckeditor4/4.9.0/guide/dev/code_documentation/README.md
Warning: Possible broken link {@linkapi CKEDITOR.whatever CKEDITOR.whatever} in ckeditor4/4.9.0/guide/dev/code_documentation/README.md
Warning: Possible broken link {@linkapi CKEDITOR.SOURCE_MODE CKEDITOR.SOURCE_MODE} in ckeditor4/4.9.0/guide/dev/code_documentation/README.md
Warning: Possible broken link {@linkapi CKEDITOR.SOURCE_MODE CKEDITOR.SOURCE_MODE} in ckeditor4/4.9.0/guide/dev/code_documentation/README.md
Warning: Possible broken link {@linkapi CKEDITOR.WYSIWYG_MODE CKEDITOR.WYSIWYG_MODE} in ckeditor4/4.9.0/guide/dev/code_documentation/README.md
Warning: Possible broken link {@linkapi CKEDITOR.parent CKEDITOR.parent} in ckeditor4/4.9.0/guide/dev/code_documentation/README.md
Warning: Possible broken link {@linkapi CKEDITOR.whatever CKEDITOR.whatever} in ckeditor4/4.9.0/guide/dev/code_documentation/README.md
Warning: Possible broken link {@linkapi CKEDITOR.skin.ua_editor CKEDITOR.skin.ua_editor} in ckeditor4/4.9.0/guide/skin_sdk/browser_hacks/README.md
Warning: Possible broken link {@linkapi CKEDITOR.on CKEDITOR.on} in ckeditor4/4.9.0/guide/dev/features/output_format/README.md
Warning: Possible broken link {@linkapi CKEDITOR.on CKEDITOR.on} in ckeditor4/4.9.0/guide/dev/howtos/dialog_windows/README.md
Warning: Possible broken link {@linkapi CKEDITOR.on CKEDITOR.on} in ckeditor4/4.9.0/guide/dev/howtos/dialog_windows/README.md
Warning: Possible broken link {@linkapi CKEDITOR.on CKEDITOR.on} in ckeditor4/4.9.0/guide/dev/howtos/dialog_windows/README.md
Warning: Possible broken link {@linkapi CKEDITOR.on CKEDITOR.on} in ckeditor4/4.9.0/guide/dev/howtos/dialog_windows/README.md
Warning: Possible broken link {@linkapi CKEDITOR.on CKEDITOR.on} in ckeditor4/4.9.0/guide/dev/howtos/output/README.md
`

**Comment by msamsel** [comment]
Umberto allows on creating link to Guides from API docs with `glink`.
for example here instead of using:
`[documentation](#!/guide/dev_acf-section-automatic-mode-but-disallow-certain-tagsproperties)`
you could link like:
`{@glink guide/dev_acf#automatic-mode-but-disallow-certain-tagsproperties documentation}`
More information here: https://github.com/cksource/umberto#links-to-guides

About other errors there is bunch of PR waiting for Review:
* https://github.com/ckeditor/ckeditor-dev/pull/1787
* https://github.com/ckeditor/ckeditor-docs/pull/143
* https://github.com/ckeditor/ckeditor-docs/pull/145

Also `CKEDITOR.on` error shouldn't be present any longer as it became merged to major already: https://github.com/ckeditor/ckeditor-dev/issues/1788

**Comment by engineering-this** [comment]
>@engineering-this please rebase your PR branch to the latest master/major (depends on @mlewand response) and verify broken link warnings from Umberto.
@jacekbogdanski:
As we are working currently on major release I've rebase it onto laster major. Currently I don't see any broken links during building process.

**Comment by mlewand** [comment]
Rebased and retargeted branch at `master`.

**Pull request merged**
