### PR TITLE
Add Pashto language

### PR DESCRIPTION
**Pull request by mnrafg**

### CODE REVIEW

**Comment by mlewand** [comment]
Thank you very much for contribution! We're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings. Please send your contribution there, so that we can pull it into upcoming release.

Thanks!

**Comment by mnrafg** [comment]
You are welcome,

I have tried to go through the recommended Transifex but while I tried to do a "Request language" action there was no Pashto language within that list.
So what should I do now?

**Comment by mlewand** [comment]
@AnnaTomanek any tips on that?

**Comment by AnnaTomanek** [comment]
Hi Muhammad,

Many thanks for your contribution, and I'm really sorry for a late reply. I must have missed the GitHub notification for this issue :(

It seems that Transifex uses the "Pushto" spelling so I added a new language team here: https://www.transifex.com/ckeditor/ckeditor/language/ps/

Can you join Transifex and the team there?

Thank you once again for your willingness to help, and sorry that it took us so long to sort out!
Do not hesitate to contact us should you need any assistance with using Transifex.

**Pull request closed without merging**
