### PR TITLE
Change links from Functionality Overview subsection to new Features section

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Task

## What changes did you make?

This is required by ckeditor/ckeditor-docs#249

### CODE REVIEW

**Comment by engineering-this** [comment]
This should be reviewed together with ckeditor/ckeditor-docs#249

**Comment by f1ames** [comment]
Now I have noticed that it is target to `master`. @engineering-this could you retarget it to `major`?

**Comment by engineering-this** [comment]
Retargeted to `major`.

**Comment by f1ames** [comment]
Rebased on the latest `major`.

**Pull request merged**
