### PR TITLE
Fix for: Failing test `tests/plugins/emoji/dropdown`

### LINKED ISSUE #2831: Failing test `tests/plugins/emoji/dropdown`
## Type of report

Failing test

## Provide description of the task

Failing test `tests/plugins/emoji/dropdown`.

The test fails on dev and built version from the dashboard.

image

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Fix failing tests

## What changes did you make?

Original issue reported only one case, however I could see three different reasons for tests to fail on Firefox.

### Emoji List is loaded asynchronously

Sometimes tests were run earlier resulting in type error. This is fixed by adding `waitForEmoji` which is delaying each test case until Emoji List is loaded. Related issue: #3094.

### After fix above some tests started to fail on Firefox, because of wrong assertion.
	- expected: `'<p>⭐</p>'`
	- actual: `'<p>⭐</p><p> </p>'`

	Fixed by adding `result.replace( regex )` to cut empty paragraph.

### Lastly the original issue.
Firefox seems to not respond very well to multiple synchronous changes of `scrollTop` of various elements, and that's what we do in our implementation of `scrollIntoView`. When this TC fails scroll position is incorrect. Fixed by calling native `scrollIntoView` for Firefox.

Additionally take a look at the code:
https://github.com/ckeditor/ckeditor-dev/blob/08ea0051cedd75c0bbb55d88d47fe9e05cddd1f5/tests/plugins/emoji/dropdown.js#L135-L137
	`scrollIntoView` is already causing a `scroll` event, so no need to manually trigger it. Although I didn't find it to interfere with tests, it's redundant so I'm removing it.

### Note
All of the issues are causing tests to fail randomly. After applying the fixes I did run tests multiple times and they seem to not fail, but Reviewer should check few times too.

Closes #2831

### CODE REVIEW

**Comment by f1ames** [comment]
Rebased and retargeted onto latest `major`.

**Comment by engineering-this** [comment]
>It looks like the test is still failing 😞

That's the problem with unstable tests, you think you fixed it, because it doesn't fail after xx runs, but it will fail when Reviewer tries it 😞

It looks like both native `scrollIntoView` and our fallback doesn't scroll correctly on Firefox. Some kind of race condition. I've tried one more thing - wrapping just the `scrollIntoView` in `setTimeout`. It seems to fix the issue.

**Comment by f1ames** [comment]
Rebased on the latest `major`.

**Comment by engineering-this** [comment]
Screenshot 2019-06-11 at 11 44 03

From dashboard it passes almost every time, but yeah it's still not stable 😡

It feels like, spending more time on trying to fix whatever is causing this test to fail is pointless, as it's caused by some browser quirk which is very hard to reproduce outside of this TC. IMO we should go with one of following:
- Ignore TC on Firefox
- Use mocked event to rework it

WDUT @f1ames ?

**Comment by engineering-this** [comment]
Ignored test on Firefox, and reverted recent changes that were aimed for FF.

**Pull request merged**
