### PR TITLE
[#14613] prevent plugin initialization if editor was already destroyed…

### PR DESCRIPTION
**Pull request by brianmay27**
…d (race condition)

### CODE REVIEW

**Comment by brianmay27** [comment]
I tried to figure out how to functional test this. I was able to reproduce this and catch the error with a event listener but could not figure out how to wait a few seconds for the call back to be called. Im happy to finish the test but need a little help :)

**Comment by brianmay27** [comment]
Any updates? We would like to get this in as we have been seeing issues around this race issue and would like to get it merged.

**Comment by mlewand** [comment]
Hi @brianmay27 - sorry for the delay, we've been pretty for a long time. We should be able to review this PR soon.

**Comment by mlewand** [comment]
I see that we need manual / unit tests - but the problem is pretty clear, so info for the reviewer: before bouncing the ticket, please give a try to reproduce it on your own, if no problem with this just create mt, and unit tests - as it should be fairly simple.

**Pull request merged**
