### PR TITLE
Fixed cloning equals nodes for correct editor.getSelection working (#16813 bug)

### PR DESCRIPTION
**Pull request by DmitryKrekota**
This is my solution to fix the bug: https://dev.ckeditor.com/ticket/16813

### CODE REVIEW

**Comment by mlewand** [comment]
Thanks for the PR @DmitryKrekota!

We need this code to be covered with tests. Please see [our dev guide](http://docs.ckeditor.com/#!/guide/dev_contributing_code) on how to create / work in test environment. So please provide tests for added code.

**Comment by DmitryKrekota** [comment]
I added test.
There were problems with 'bender server run' command becouse of out of date socket.io dependency in benderjs module. To resolve the problem I put latest version of socket.io to /node_modules/benderjs/node_modules/ instead of old socket.io. It seems that benderjs needs to update dependencies. Maybe it is because of my node version - 7.4.0 :)

**Comment by mlewand** [comment]
@DmitryKrekota Thanks for tests! Let's make sure it gets reviewed.

**Comment by DmitryKrekota** [comment]
@mlewand can you review and marge my PR?

**Comment by mlewand** [comment]
Hi @DmitryKrekota, sorry for the time it took us to get back to you.

I have actually good news, the bug has been fixed in other issue some time ago, and is no longer reproducible with our latest release 🎉 Now for clarity I'll put repro steps and online demos that do not require zip downloads.

## Repro steps

1. Select first word ("foo") with a double click.
1. Click the styles dropdown.
1. Close it with `esc` key.
1. Copy the selected text with `ctrl/cmd+c`.
1. Paste the text with `ctrl/cmd+v`.

### Expected

Only "foo" is being pasted.

### Unexpected

"foo bar" is being pasted.

## Online demos

Here are two samples:

* [CKEditor 4.7.1](https://codepen.io/mlewand/pen/xJqzQq) - this is where the issue was last reproducible
* [CKEditor 4.7.2](https://codepen.io/mlewand/pen/ZjeodZ) - this is where the issue was first fixed

**Pull request closed without merging**
