### PR TITLE
Fix #14590

### PR DESCRIPTION
**Pull request by dpidcock**
Actually fix the problem, which was caused by not resetting the "needsSpace" variable when "reset" was called.

### CODE REVIEW

**Comment by Tade0** [comment]
Thank you for the PR!

Looks like this one works nicely. I'm seeing that JSCS has a few complaints, though. Would you mind if I asked you to correct those?
Here's how the JSCS output looks:
```
Running "jscs:git" (jscs) task
Illegal space before opening round brace at tests/plugins/htmlwriter/htmlwriter.js :
     2 |/* bender-ckeditor-plugins: wysiwygarea, htmlwriter */
     3 |bender.test( {
     4 | 'test extra line break': function () {
------------------------------------------^
     5 |  var data = '<div>Text <strong>inline</strong> Text <p>paragraph</p></div>';
     6 |
Illegal space before opening round brace at tests/plugins/htmlwriter/htmlwriter.js :
    13 |
    14 |    on: {
    15 |     instanceReady: function ( evt ) {
------------------------------------^
    16 |      evt.editor.dataProcessor.writer.setRules('p', {
    17 |       indent: true,
Missing space after opening round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    14 |    on: {
    15 |     instanceReady: function ( evt ) {
    16 |      evt.editor.dataProcessor.writer.setRules('p', {
-------------------------------------------------------^
    17 |       indent: true,
    18 |       breakBeforeOpen: true,
Missing space before closing round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    20 |       breakBeforeClose: true,
    21 |       breakAfterClose: true
    22 |      });
---------------^
    23 |
    24 |      evt.editor.dataProcessor.writer.setRules('div', {
Missing space after opening round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    22 |      });
    23 |
    24 |      evt.editor.dataProcessor.writer.setRules('div', {
-------------------------------------------------------^
    25 |       indent: true,
    26 |       breakBeforeOpen: false,
Missing space before closing round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    28 |       breakBeforeClose: false,
    29 |       breakAfterClose: true
    30 |      });
---------------^
    31 |     }
    32 |    }
Illegal space before opening round brace at tests/plugins/htmlwriter/htmlwriter.js :
    32 |    }
    33 |   }
    34 |  }, function ( bot ) {
---------------------^
    35 |   bot.setData( data, function () {
    36 |    var afterFormat = bot.getData(false, false);
Illegal space before opening round brace at tests/plugins/htmlwriter/htmlwriter.js :
    33 |   }
    34 |  }, function ( bot ) {
    35 |   bot.setData( data, function () {
--------------------------------------^
    36 |    var afterFormat = bot.getData(false, false);
    37 |
Missing space after opening round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    34 |  }, function ( bot ) {
    35 |   bot.setData( data, function () {
    36 |    var afterFormat = bot.getData(false, false);
------------------------------------------^
    37 |
    38 |    // Trigger getData a second time to reveal bug.
Missing space before closing round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    34 |  }, function ( bot ) {
    35 |   bot.setData( data, function () {
    36 |    var afterFormat = bot.getData(false, false);
------------------------------------------------------^
    37 |
    38 |    // Trigger getData a second time to reveal bug.
Missing space after opening round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    37 |
    38 |    // Trigger getData a second time to reveal bug.
    39 |    assert.areSame( afterFormat, bot.getData(false, false) );
-----------------------------------------------------^
    40 |   } );
    41 |  } );
Missing space before closing round bracket at tests/plugins/htmlwriter/htmlwriter.js :
    37 |
    38 |    // Trigger getData a second time to reveal bug.
    39 |    assert.areSame( afterFormat, bot.getData(false, false) );
-----------------------------------------------------------------^
    40 |   } );
    41 |  } );
>> 12 code style errors found!
```

**Comment by dpidcock** [comment]
No problem.  I wasn't sure what format rules you were using, so I tried guessing from the existing code base. 
 
 If I install jscs (npm install .. right?)  do I need to configure it differently from the default?

**Comment by dpidcock** [comment]
BTW - I have already updated to conform

**Comment by mlewand** [comment]
@Tade0 Could you check it?

**Comment by Tade0** [comment]
It's clean, thank you @dpidcock!

**Comment by dpidcock** [comment]
When might this be in a release?

**Comment by mlewand** [comment]
@dpidcock It's scheduled for 4.5.10. Originally 4.5.10 was meant to be a micro release in next week, however we'll most likely reschedule this release. Can't give you more details at this point.

**Comment by Tade0** [comment]
This one was merged a while ago. Closing.

**Pull request closed without merging**
