### PR TITLE
50 shades of gray

### PR DESCRIPTION
**Pull request by mizafish**
Fill the row with gray cells

### CODE REVIEW

**Comment by mizafish** [comment]
Fill the row with gray cells.

**Comment by chrisgraham** [comment]
@Reinmar haha #punsNeedToBeAcknowledged

**Comment by Reinmar** [comment]
> @Reinmar haha #punsNeedToBeAcknowledged

:)

Thanks for the PR. I'm not sure now when we'll be able to truly review it, because we're now totally devoted to finishing CKEditor 4.5.0, but if not before closing it, then shortly after that.

**Comment by pjasiun** [comment]
I have reviewed your changes, added one more commit and closed it as a [#13266](http://dev.ckeditor.com/ticket/13266#comment:2) ticket. Changes will we available in the next release ([4.4.8](http://dev.ckeditor.com/query?group=status&milestone=CKEditor+4.4.8)). Thank you for the contribution.

**Pull request closed without merging**
