### PR TITLE
Fixed protection pattern for attributes

### PR DESCRIPTION
**Pull request by asmforce**
Added support for self-closing tags (otherwise a protection pattern isn't being changed and un-protection will fail)

### CODE REVIEW

**Comment by Reinmar** [comment]
Thanks for the patch. We will need two more things to be able to accept it:

* Description of the bug that this patch fixes or a ticket from http://dev.ckeditor.com.
* Tests for the patch. See the [Testing Environment](http://docs.ckeditor.com/#!/guide/dev_tests) guide and check [this file](https://github.com/ckeditor/ckeditor-dev/blob/master/tests/core/htmldataprocessor.js).

**Comment by asmforce** [comment]
I use a source protection inside a tag's attribute:


The self-closing (standalone) tag contains a slash before right angle bracket. We could use a spaces before it (or not use):



The first one is ok but the second causes a wrong behavior. I get the following result after toDataFormat:


My PR fixes that.
Also I added an appropriate changes to tests/core/htmldataprocessor.js (already available in this PR).

Have a look please.

**Comment by Reinmar** [comment]
I confirmed the issue and reported the ticket: http://dev.ckeditor.com/ticket/13292

**Comment by Reinmar** [comment]
I pushed https://github.com/cksource/ckeditor-dev/tree/t/13292 with your patch plus some my tests improvements. Everything looks good, but I've been wondering whether we can make only the last of these 4 changes. AFAICS adding `\/?` at the end solves the issue and doesn't break any other test. Are you aware of any cases where that could fail?

**Comment by asmforce** [comment]
If we left a \/? only at the end, regex would match an invalid HTML tags.
E.g.
`<tagname attr1='val1' / />`

To be honest I'm not sure if that behavior is is better or worse. ;)

**Comment by Reinmar** [comment]
Good point. I think it's better if it matches more tags – even invalid ones. Especially that right after these regexps we pass the data through a native DOM element and browsers fix small glitches. I'm not sure about this one, but that doesn't matter.

So to merge this PR we only need to simplify the change in the regexp and run tests. We'll handle this.

**Comment by Reinmar** [comment]
Merged to master with a2ff7bf. Thanks!

**Pull request closed without merging**
