### PR TITLE
Support for Clipboard API in Edge

### LINKED ISSUE #468: Support for Clipboard API in Edge
## Are you reporting a feature or a bug?

Task
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/16994

## Description

[New Edge 15 ​implemented Clipboard API](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6515107-clipboard-api), so it will be nice to switch from our pastebin to real API in this browser.

Note however that users report some errors (see comments in the linked thread).

## Other details

* Browser: Edge 15+
* OS: Windows 10

### PR DESCRIPTION
**Pull request by f1ames**
## What is the purpose of this pull request?

New feature

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests) and
[how to create tests](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

Closes #468, #921.

### CODE REVIEW

**Comment by f1ames** [comment]
On this branch no changes were made directly. All changes were done and already reviewed on #968. To close it we still need fix for #1047 as mentioned in https://github.com/ckeditor/ckeditor-dev/pull/1105#issuecomment-343530942.

**Comment by f1ames** [comment]
As #1047 is no longer reproducible on latest Edge version (https://github.com/ckeditor/ckeditor-dev/issues/1047#issuecomment-343917789), we are ready for merge.

**Comment by f1ames** [comment]
Since #1160 was merged, I think we are ready for final review and merge to `major`.

**Comment by mlewand** [comment]
@f1ames correct, sorry did not mark my assignee in TP 🙂 finishing unit test runs.

**Pull request merged**
