### PR TITLE
Set toolbarconfigurator button "type" attribute

### PR DESCRIPTION
**Pull request by colemanw**
Love the new configurator! I've had good success integrating it with our [php-based CRM](https://civicrm.org/blogs/colemanw/big-changes-wysiwyg-editing-47) to allow users to configure their editing experience in-app. One little problem was that the missing "type" attribute on the buttons would cause premature form submission. Thanks for considering this change.

### CODE REVIEW

**Comment by Reinmar** [comment]
Thanks! :) We're glad people like it and that it's also helpful for other projects.

**Comment by Reinmar** [comment]
Changelog entry in a4c9294525faae.

**Comment by colemanw** [comment]
Thanks for the merge @Reinmar. For my future reference is submitting a PR like this the right way to send in fixes or should I open an issue instead?

**Comment by Reinmar** [comment]
This one was ok to be closed this way, because it was not related to the editor itself, but samples and it was a simple thing. But in >99% cases we would need a ticket on http://dev.ckeditor.com, although, if a PR is clear for us (it includes a proper description), we can open that ticket ourselves. Not a big deal.

You can find more details about contributing code in docs.ckeditor.com/#!/guide/dev_contributing_code

**Pull request merged**
