### PR TITLE
optimized all images

### PR DESCRIPTION
**Pull request by TheDigitalOrchard**
Compressing reduced images by an average of 40.7%, with some being compressed up to 88.8%! (good for the web).

### CODE REVIEW

**Comment by TheDigitalOrchard** [comment]
Sample showing the results of running images through ImageOptim.

ckeditor-image-compression

**Comment by TheDigitalOrchard** [comment]
My GitHub skills have faded and I'm not familiar with CKEditor PR guidelines. Did you want this commit to go to master or another branch?

**Comment by Reinmar** [comment]
Thanks for the PR, but unfortunately we cannot accept it. See https://github.com/ckeditor/ckeditor-dev/pull/150#issuecomment-66914036 for more details why.

**Comment by TheDigitalOrchard** [comment]
OK, thanks for letting me know. I will optimize my own downloads until you have this functionality incorporated into your Builder process.

**Pull request closed without merging**
