### PR TITLE
Fix typo in inline code snippet

### PR DESCRIPTION
**Pull request by benjy**
## What is the purpose of this pull request?

Typo fix

### CODE REVIEW

**Comment by msamsel** [comment]
Hi @benjy,
thank you very much for your contribution. We still need for your CLA signature to have possibility to merge your changes with CKEditor. :) I hope it won't be a problem in this case.

**Comment by benjy** [comment]
Sure, are you emailing the details?

**Comment by mlewand** [comment]
@benjy CLA could not be sent because you have masked email. Please either:

* Share your email address through [our contact form](https://cksource.com/contact) (use inquire type "other" and link to this PR).
* Unmask your email.

Choose whatever works better for you. Sorry for so much hassle for such a small change... 😉

**Comment by benjy** [comment]
I've signed the document, it was a little convoluted, a bit of political correctness gone mad I think!

**Comment by mlewand** [comment]
Thanks for the contribution @benjy. Sorry for the formal part, but we simply need them for accepting any work. And clearly our CLA system needs a better handling for masked mails, as it's not uncommon to use it (I'm using it myself 😉).

**Pull request merged**
