### PR TITLE
T/12542

### PR DESCRIPTION
**Pull request by drfisher**
Hello!
I need an ability to create multiple nested editable areas of same type in one widget.
See http://dev.ckeditor.com/ticket/12524
In addition an 'editableKey' event was added.

### CODE REVIEW

**Comment by zipp3r** [comment]
@Reinmar, hello! This is a continuation of my request #167. Now all tests pass.

**Comment by Reinmar** [comment]
Thanks! We're releasing 4.4.8 and 4.5.0 today, so we're quite busy atm, but we'll get back to your PR as soon as we're done with them.

**Comment by Reinmar** [comment]
Hi!

I've reviewed your patch. It's a good start, but we need to shape it well, to avoid problems with existing widgets. I described how we would see it in http://dev.ckeditor.com/ticket/12524#comment:3. There are some differences in the details – e.g. that singular editables should be still accessible in the same way, and that the whole feature should be opt-in. Also, we must not overcomplicate existing methods like `initEditable()`.

Moreover, I believe that while merging major to your branch you lost big part of your changes at some point. Currently your branch contains only changes in initEditable(), but I can see that you committed more than that.

Please also note that we will need tests for all the new methods and changes in existing ones. Without a proper code coverage we cannot accept the patch.

And finally, please check [how to contribute code](http://docs.ckeditor.com/#!/guide/dev_contributing_code) for some details regarding setting up dev env.

**Comment by drfisher** [comment]
Hi, @Reinmar!

Sorry for the late response.

We've merged actual major branch into t/12542, added tests and we've done all requirements.

**Comment by zipp3r** [comment]
Hello there! Anybody can review our request?

**Comment by zipp3r** [comment]
The branch is gonna to start to smell :(

**Comment by drfisher** [comment]
This pull request continues here https://github.com/ckeditor/ckeditor-dev/pull/321

**Pull request closed without merging**
