### PR TITLE
GH template improvements

### PR DESCRIPTION
**Pull request by jacekbogdanski**
Small adjustments to remove duplication.

### CODE REVIEW

**Comment by f1ames** [comment]
I have added default labels and change template names so they are ordered like:

1. Bug
1. Feature
1. Docs
1. Security
1. Task

Can you take a look @jacekbogdanski?

**Comment by jacekbogdanski** [comment]
I'm wondering about pushing security even lower, thus it's actually warning rather than a functional button. WDYT?

**Comment by f1ames** [comment]
@jacekbogdanski I was thinking about it, but tasks are usually only reported by us and security issues are also reported by community so I think it should be higher.

**Comment by jacekbogdanski** [comment]
Makes sense and looks fine :+1:

**Pull request merged**
