### PR TITLE
Support for "bodyClass" and "bodyId" settings in Styles dropdown

### PR DESCRIPTION
**Pull request by aik099**
Closes https://dev.ckeditor.com/ticket/7452

### CODE REVIEW

**Comment by aik099** [comment]
Any updates?

**Comment by Tade0** [comment]
Thanks for the PR!

Would you like to help us further by including some tests(a manual test is fine in this case).

Here's a guide just in case: http://docs.ckeditor.com/#!/guide/dev_contributing_code

**Comment by aik099** [comment]
I'm new to CKEditor. Is there any manual (I haven't found `CONTRIBUTING.md` file in the repo itself) about how to write tests?

**Comment by aik099** [comment]
What you mean by manual test. Using provided link I've found explanation how to create tests using Bender, but not manual ones.

**Comment by mlewand** [comment]
@aik099 Now I can see it's not exposed well enough, there's a paragraph:

> Some type of features or bugs cannot be tested automatically. In such cases, make sure to create a manual test (see this one for instance).

Which links to https://github.com/ckeditor/ckeditor-dev/tree/master/tests/tickets/12735 as an example. This helps us more quickly to check if the code actually fixes the problem for end user, and is also used by QA again during the final release.

I'll make sure that docs get updated there.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you and the tests were not added. We're closing this PR for now. Still, feel free provide us requested feedback, so that we can reopen this PR.

**Pull request closed without merging**
