### PR TITLE
Update Bulgarian translation

### PR DESCRIPTION
**Pull request by nmpetkov**
Translation of missing keys and corrections to existing.

## Does your PR contain necessary tests?
- [ ] Unit tests
- [ x] Manual tests OK

### CODE REVIEW

**Comment by f1ames** [comment]
Thank you very much for contribution! We're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings. Please send your contribution there, so that we can pull it into upcoming release.

Thanks!

**Comment by nmpetkov** [comment]
Sorry to learn for  your project on transifex for localisation after finishing the work.
Is there any way of easy transfer of translated strings from this PR or I have to copy one by one to respective files and lines?

**Comment by AnnaTomanek** [comment]
Hi @nmpetkov,

first of all, thanks again for your help! As @f1ames explained, we handle CKEditor localization through Transifex. However, you did a huge job here and the effort to manually copy all entries to Transifex would make little sense, so we'll try to figure it out by ourselves and transfer your translations.

Meanwhile, we'll be most happy if you joined us at Transifex to work on further improvements. [CKEditor 5 Bulgarian translation](https://www.transifex.com/ckeditor/ckeditor5/language/bg/) is still incomplete! :)

**Comment by nmpetkov** [comment]
Thank you for trying to accept translations in this way.
I already joined Transifex  and CKEditor project and will wait to see updated files there to continue to work on BG translation.

**Comment by nmpetkov** [comment]
I am not still seeing any changes to Transifex translations. Please inform me what to do next.

**Comment by AnnaTomanek** [comment]
We'll work on it next week, thanks for staying vigilant :)

**Comment by nmpetkov** [comment]
I made translations in Transifex.
Hope to see in files.

**Pull request closed without merging**
