### PR TITLE
Retina (hidpi) support for Kama theme

### PR DESCRIPTION
**Pull request by chrisgraham**
Enjoy :).

### CODE REVIEW

**Comment by Reinmar** [comment]
Related ticket: http://dev.ckeditor.com/ticket/12918

**Comment by oleq** [comment]
I'd like to start off by thanking you for your contribution. It is quite a piece of work you did in this PR and CKEditor team really does appreciate it!

However, as I reviewed your HiDPI icons, I found out that they are noticeably different than corresponding low-resolution originals. Those details make your work a different icon set despite the evident resemblance to Kama, which is, sadly, the reason why we cannot accept it.

12918-diff-loop

But don't worry! It would be a shame if so much work was done for nothing. You should [add it](http://ckeditor.com/add/skin) to the official [CKEditor Addons list](http://ckeditor.com/addons/skins/all) and make it available for anyone, i.e. in [CKEditor Builder](http://ckeditor.com/builder).

Thank you again!

**Comment by chrisgraham** [comment]
Well, in most cases it is additional detailing, or aligning stuff better (due to a bigger canvas), which you'd expect on a higher resolution. The link/unlink/find/print/clipboard icons could you a little tuning. I have tried to bring a number of user experience problems affecting people downstream to your attention, but I keep coming up against barriers - it just doesn't seem collaborative I'm afraid. So why not allow this to be an active discussion rather than a CKSource vs external entity situation?

Doing extra work to lead to extra fragmentation is a non-starter for me; everyone wanting the retina icons would need to choose special options, and the icons would need to be kept under ongoing maintenance across CKEditor versions. I want to help you make CKEditor a smoother more-pleasant experience for both users and developers, rather than add complexity.

**Comment by fredck** [comment]
Chris, don't get it wrong, really. I will try to put it in a different way, even if I'm entering into a very delicate subject. So please take it positively.

I believe the whole point is that the quality of the contribution doesn't match the high standards that we're setting for CKEditor today. Therefore we cannot accept it with a "just to be nice with the contributor" approach, even if we appreciate immensely the effort you've put on it. We feel very bad to have to do so, especially when someone that contributed so much to the project is involved.

That's the role of CKSource, in fact. We have a team of developers dedicating their lifes to CKEditor with the main scope of making it a successful project. If you follow the way we work, we're very strict also inside of the team and so having code or ideas refused is just part of our everyday work. All for the benefit of CKEditor, ensuring a quality rock solid solution.

Feel free to comment if you think that we're doing it wrong or if you have suggestions.

**Comment by Reinmar** [comment]
I have to say that it is the biggest contribution to CKEditor since I joined the project 3.5 year ago. I know how much time it takes to create so many icons and I would love if CKEditor had them. However, we want to keep the project's level as high as possible. Taking shortcuts, like accepting PRs which are slightly below this level, may seem to be harmless and desirable, because some issue is (partially) fixed, but in a longer perspective that doesn't really work. Once a project starts to have flaws which aren't quickly mended it is natural for the general quality level to drop. It is a common psychological pattern which was described very well in [Pragmatic Programmer](https://pragprog.com/the-pragmatic-programmer) book. CKEditor of course isn't perfect and there are many issues that could be fixed, but it doesn't mean that we should not care about quality of what we do. This is the reason why we are so pedantic when it comes to a code style or tests - everything must be green. And it really is although it takes a significant effort. But no one said that it will be easy :).

Anyway, it is sad when we cannot accept a contribution but it is a necessary precaution. If you are willing to spend some more time on this, @oleq should explain what are the minimum improvements that will be needed. I would also propose to not close PRs which didn't pass the review, but keep them open so their authors or other developers can continue the work. A closed PR can always be reopened, but it may seem that it was totally rejected, while in this case it wasn't.

> I have tried to bring a number of user experience problems affecting people downstream to your attention, but I keep coming up against barriers - it just doesn't seem collaborative I'm afraid. So why not allow this to be an active discussion rather than a CKSource vs external entity situation?

I am not sure if I understand what you mean. We cofirmed many of [your tickets](http://dev.ckeditor.com/query?status=assigned&status=closed&status=confirmed&status=new&status=pending&status=reopened&status=review&status=review_failed&status=review_passed&reporter=Chris+Graham&order=priority), discussions were [very active](http://dev.ckeditor.com/ticket/12904) and we wanted to accept this PR. It was rejected not because some CKSource company didn't like it, but because CKEditor core developers, those with the biggest knowledge and experience with CKEditor, said that it does not meet the project's standards. If there were more meritorious developers, votes of all of them would count, regardless of their companies. What's more - if we'll see that the community wants this PR to be accepted, it would be accepted. But CKEditor is a very specific project, which requires very uncommon knowledge, so the community focus mainly on reporting issues (which is extremely helpful of course), hence all the experienced CKEditor developers work for CKSource. We are open to any ideas on how this situation could be improved, but that's the status of things right now. For instance, we are trying to keep everything open, but if you miss some information, then let us know.

**Comment by Reinmar** [comment]
@fredck, mine post is longer! :D

**Comment by fredck** [comment]
@Reinmar, we hit ENTER at the very same time :D... good to see that we're at least aligned in the way of seeing this.

**Comment by chrisgraham** [comment]
Hi guys. Nobody would expect you to accept a contribution that wasn't up to standard. Just don't be so final about it by closing the PR (as @Reinmar pointed out). Leave scope for a conversation so we can polish it off, and be inclusive about it all. My end took this much time, we can spend some more. Oh, and try not to leave huge amounts of time without discussion so that coming back to it is like taking up a cold case ;). I will get our designer to come back to this when he is free from what he's currently working on.

"I am not sure if I understand what you mean. We cofirmed many of your tickets, discussions were very active" - it just seemed whatever I opened up, it was either left crappy while some other thing with no clear implementation schedule is worked on, or was left confirmed but without being assigned even though it would take 5 minutes to fix, or not particularly acknowledged as a major issue (when I know it causes major pain to users). But obviously I'm coming from a point of frustration here ;-). It would be nice to see things assigned and tagged quickly. JetBrains are good at this for example, they'll confirm an issue then do a good job of visibly tying it into their plans via roadmap tags and descriptive tags.

"But CKEditor is a very specific project, which requires very uncommon knowledge, so the community focus mainly o n reporting issues (which is extremely helpful of course), hence all the experienced CKEditor developers work for CKSource" - It doesn't need to be like that. I am not one to talk, as it's just the same with my company, but as a down-stream app used by many projects/companies there is great scope for more people to contribute. Who works on the Linux kernel ;-)?

**Comment by Reinmar** [comment]
> Oh, and try not to leave huge amounts of time without discussion so that coming back to it is like taking up a cold case ;).

This is a thing that I always had problem with. There are 3-4 developers right now capable of reviewing PRs, but their availability isn't good. I hate leaving a PR for a month or more, but doing a review requires a significant amount of time, so you need to stop whatever you were doing. And really, we are talking here about 1h+, so taking into account how many things happen on Trac and here, it's a lot. I think though, that there is a room for improvements. Perhaps we may force a rule that every day starts from PR&ticket reviews.

> it just seemed whatever I opened up, it was either left crappy while some other thing with no clear implementation schedule is worked on, or was left confirmed but without being assigned even though it would take 5 minutes to fix

Wow... that's kind of unfair.

* First thing is - only typos take 5 minutes to fix. If a fix requires code changes it is 1h+ due to review, tests, etc. Usually a bug fix is around 4-6h of work (talking here about a median, because minimum is about 1h, maximum is about few weeks (no joking)).
* CKEditor is a free and open source software, not like mentioned by you JetBrains' products. There are limited resources and we are doing our best to channel them into the right issues.
* What are the "right" issues? Of course you could find a hundred issues that look to be "1h", but if we'll start working only on them we will never be able to work on a bigger things which may be far more important for users and developers. So instead, we sort things by how important they are for developers and users. It means that many small issues will never be fixed, but at the same time we are able to fix issues which occur to many developers. PS. Voting on tickets (by commenting and keeping them alive) is the best way to show us what should be fixed next.

> Who works on the Linux kernel ;-)?

Big companies. I don't know the situation there very well, but most of the hardcore OSS projects are developed by cooperation of big companies like Oracle, IBM, HP, etc... Simply because there are not enough super-high-quality-developers who are able to voluntarily maintain such complex systems. It does not deny the idea of OSS, but it's just the hard reality. The more complex the project is the smaller part of the community is able to help (except reporting bugs). Fortunately, CKEditor is not thaaat hard, so we really believe that [CKEditor 5](https://github.com/ckeditor/ckeditor5) will attract more active developers.

**Comment by Reinmar** [comment]
We shouldn't close this issue, because we are still very interested in accepting this PR. It just needs some tweaks here and there. @oleq, could you list buttons that need to be tuned up the most?

**Comment by oleq** [comment]
Hi Chris! 

I checked your icons, one by one, and summarized all the differences between Lo– and Hi–DPI that do really matter. With the exception of **find** button, those are **technically** minor issues (mostly). Nevertheless, it is important for us, to reduce differences to minimum and keep both sets coherent if they are to be redistributed as a part of the core.

Here's the list of what needs to be improved. I hope it's helpful for you or your graphic designer:



* **save**: shape, colors,
* **preview**: shape, translucent magnifying glass,
* **print**: shape, colors,
* **cut**: shape of the scissors,
* **paste (all 3 buttons)**: shape, missing left and top-left border of the icon,
* **find**: it's a different icon,
* **selectall**: size, width of the inner stripped box,
* **scayt/wsc**: font family,
* **checkbox**: size,
* **hiddenfield**: text, font weight,
* **bold, italic, underline**: font weight,
* **subscript, superscript**: font family, shape,
* **bidiltr, bidirtl**: shape, color of "the triangle",
* **link, unlink**: color set, shape and style of "the chain",
* **anchor**: shape of the flag,
* **image**: size of an image,
* **flash**: background gradient, dark outline of "f",
* **pagebreak**: colors,
* **maximize**: shape, colors,
* **showblocks**: color of the letter, border color and shading, also see: **preview**,
* **help**: font family,
* **placeholder**: font weight

I'd appreciate your feedback. If something about the list is not clear, I'm ready to explain and I hope things will smooth out soon.

**Comment by chrisgraham** [comment]
Ok thanks, I'll ask our designer to go back over these. Just FYI it'll probably be a couple of weeks as he's currently engaged in another design project.

**Comment by oleq** [comment]
@chrisgraham No problem – there is no "ASAP pressure". Take your time.

**Comment by chrisgraham** [comment]
For reference the 1st of the 3 rows has the comparison order inverted compared to rows 2 & 3.

**Comment by chrisgraham** [comment]
Icons are now updated, please re-review :).

**Comment by chrisgraham** [comment]
We've just realised we missed out updating the rtl versions. So we'll sort this out soon too.
(anchor-rtl, find-rtl, paste-rtl, pastefromword-rtl, pastetext-rtl, redo-rtl, showblocks-rtl, undo-rtl)

**Comment by chrisgraham** [comment]
RTL icons now fixed :). Fully ready for re-review now.

**Comment by oleq** [comment]
Thank you Chris! The icons look great! 

But there are still some minor issues in CSS which must be fixed before we merge your commits into master:

1. [Media queries](https://github.com/ocproducts/ckeditor-dev/commit/4e1acc84782b52915066dff5f9fa0106874070ac#diff-77b4747ce61389cb80d04c5df09b0ac8R208) should be replaced with [`.cke_hidpi` class](https://github.com/ckeditor/ckeditor-dev/blob/71574922a1daf3fcb5063d23ef28c5a3b66fb525/skins/moono/dialog.css#L342). It's shorter, maintainable and fully compatible with `CKEDITOR.env.hidpi` flag, which is used in many places, i.e. to load proper button icons.

2. In some cases, like [`.cke_inner` styled by gradients](https://github.com/ocproducts/ckeditor-dev/commit/4e1acc84782b52915066dff5f9fa0106874070ac#diff-e168fd53a26c13af4ce6e5ff320f7890R71), including another CSS selector (either using `.cke_hidpi` or media query) with `background-image` overrides gradients, i.e.

  ```
.cke_inner { gradient definitions }
.cke_hidpi .cke_inner { background-image: url( url to hidpi sprite) } // now using image sprite instead of gradients in modern and legacy browsers 
```

 In CKEditor, we use CSS gradients rather than image sprites, so HiDPI enhancements must be smart enough to respect that. I think that a simple extraction like

   ```
 .cke_inner { background-image: url( url to LowDPI sprite) }
 .cke_hidpi .cke_inner { background-image: url( url to HiDPI sprite) }
 .cke_inner { gradient definitions }
 ```
 would do the trick and HiDPI sprite would be loaded in legacy browsers only.

 I see that the same thing happens with [`.cke_combo_button`](https://github.com/ocproducts/ckeditor-dev/commit/4e1acc84782b52915066dff5f9fa0106874070ac#diff-e774046d1eecf0a7f3716099976970c3R75) and `.cke_toolgroup`. In the latter, you used `background` in your media query, which completely overrides default `background-repeat` and `background-position`, so:

screen_shot_2015-05-27_at_17 20 08

Thank you!

**Comment by chrisgraham** [comment]
Hi,

I've just pushed fixes for those issues. If you find anything small still needs tweaking please can you do it on your end during merge, as I am totally swamped with stuff to do at the moment.

**Comment by chrisgraham** [comment]
Any update on getting this merged?

**Comment by Reinmar** [comment]
We've done some more work on this and I reviewed the patch. Unfortunately there's still more work needed. Please see http://dev.ckeditor.com/ticket/12918#comment:11

**Comment by f1ames** [comment]
Hi,
Thank you for supporting Open Source and contributing to the CKEditor 4 project!
It's been a while since we last heard from you. We're closing this PR for now. Still, feel free to provide us with the requested feedback so that we can reopen this PR. Thank you!

**Pull request closed without merging**
