### PR TITLE
Make non-break space and non-break hyphen available in special chars

### PR DESCRIPTION
**Pull request by gbastien**
Hi,

this is about https://dev.ckeditor.com/ticket/13733

This is my first commit on ckeditor, I tried to follow conventions, do not know about :
- need to update other languages?

Could you please review/comment/merge?

Thank you!

Gauthier

### CODE REVIEW

**Comment by Reinmar** [comment]
Hi, thanks for the PR!

Please see http://docs.ckeditor.com/#!/guide/dev_contributing_code. Especially the part about the code style will be important. You changed the indentation few times, so it'd be best if you could propose the PR one more time, so there's only one commit.

Second thing is that the change should be minimal, so e.g. please don't touch other language strings (those that aren't related to the characters which you added).

We will also need a manual test (like here: https://github.com/ckeditor/ckeditor-dev/pull/213#issuecomment-138571467).

**Comment by gbastien** [comment]
Hi @Reinmar 

ok, I will propose a new PR with one single commit.

OK, actually I corrected a translation problem in the french version, should I make a separate PR?

I will try to see how to add a manual test.

Thank you for review,

Gauthier

**Comment by AnnaTomanek** [comment]
Hi Gauthier,

In general, we manage the localization process through the [CKEditor UI Translation Center](https://www.transifex.com/projects/p/ckeditor/) at Transifex. We do have the [French language group](https://www.transifex.com/ckeditor/ckeditor/language/fr/) there, so it would be really cool if you wanted to join us there and submit your corrections. Thanks!

**Comment by gbastien** [comment]
@AnnaTomanek I will just manage PR related translations and update the others using tx, I will join the french team.

@Reinmar I will propose a new PR today with strictly necessary code changes.

Thank you for advices,

Gauthier

**Comment by gbastien** [comment]
I close this and will propose another PR sool...

Gauthier

**Pull request closed without merging**
