### PR TITLE
Removed duplicated lang entry for clipboard

### LINKED ISSUE #1713: Duplicate "Paste" language string in Clipboard plugin
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

When adding the Paste dialog back, we created new language strings and duplicated "Paste".

```
paste: 'Paste',
...
title: 'Paste'
```

### Expected result

The existing language string should be reused, with meta language string expanded.

### Actual result

Translation progress is down for all languages and all localizations have an untranslated entry where, in fact, there is often the correct translation already available **in the same file**.

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Task

## What changes did you make?

Removed duplicated lang entry for the clipboard plugin.

Closes #1713

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
Are these the only ones (Afrikaans, Estonian)? I'll contact our translators and get back to you with the correct choice.

**Comment by mlewand** [comment]
@AnnaTomanek there are four langs that have a different values:

```
lang af.js has a difference
paste: " 'Plak'"
title: " 'Byvoeg'"

lang et.js has a difference
paste: " 'Aseta'"
title: " 'Asetamine'"

lang lv.js has a difference
paste: " 'Ielīmēt'"
title: " 'Ievietot'"

lang ro.js has a difference
paste: " 'Adaugă din clipboard'"
title: " 'Adaugă'"
```

**Comment by AnnaTomanek** [comment]
Thanks, contacted the Romanian and Latvian translators, too.

**Comment by AnnaTomanek** [comment]
Latvian: drop `Ievietot`, leave `Ielīmēt`.

**Comment by AnnaTomanek** [comment]
Romanian: drop `Adaugă din clipboard`, leave `Adaugă`.

**Comment by AnnaTomanek** [comment]
Afrikaans: leave `Byvoeg`. This was actually already done in Transifex.

**Comment by mlewand** [comment]
@jacekbogdanski please update the PR to reflect changes above.

**Comment by jacekbogdanski** [comment]
I updated lang entries during rebase.

**Comment by mlewand** [comment]
Changed the base branch, and rebased it onto the latest `major`.

**Pull request merged**
