### PR TITLE
Add icons property to class pluginDefinition

### LINKED ISSUE #2947: Icons property does not exist on class pluginDefinition
## Type of report

Bug

Creating a custom plugin as described in the [tutorial](https://ckeditor.com/docs/ckeditor4/latest/guide/plugin_sdk_sample_1.html#plugin-source-code), shows that an icons property can be defined but no such property is mentioned in the [pluginDefintion class](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_pluginDefinition.html). So, when adding a icon property in the custom plugin, typescript flags the following error: 

```
error TS2345: Argument of type '{ icons: string; init: (editor: editor) => void; }' is not assignable to parameter of type 'pluginDefinition'.
  Object literal may only specify known properties, and 'icons' does not exist in type 'pluginDefinition'.
```

## Provide detailed reproduction steps (if any)

1. Create a custom plugin with icons specified (same as tutorial [here](https://ckeditor.com/docs/ckeditor4/latest/guide/plugin_sdk_sample_1.html#plugin-source-code))
2. Compile the typescript file having the plugin definition

### Expected result

No error should be raised complaining about missing icons property.

### Actual result

Error is flagged that icons does not exist in type pluginDefintion.

## Other details

* Browser: Chrome v72.0.3626.109
* OS: Ubuntu
* CKEditor version: 4.9.2
* Installed CKEditor plugins: sharedspace

### PR DESCRIPTION
**Pull request by rafalk342**
## What is the purpose of this pull request?

Property didn't exist even though it is used heavily.

## What changes did you make?

I added icons property to type pluginDefinition and documented the changes.

Closes #2947

### CODE REVIEW

**Comment by rafalk342** [comment]
@f1ames When can I expect a review?

**Comment by rafalk342** [comment]
> Hello, thanks for your contribution!
> 
> I'm missing information about the usage of this property. You are mostly passing `icons` inside plugin definition to set icons for toolbar buttons, which will recognize plugin icon by button name. You can see some examples for [justify](https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/justify/plugin.js) plugin where multiple icons are used for a single plugin.
> 
> Also, it makes sense to attach information about icons localization using file system tree structure, e.g:
> 
> * `plugins/`
>   
>   * `myPlugin/`
>     
>     * `icons/`

Hello!
Thanks for review.

Usage is written as follow:
https://github.com/ckeditor/ckeditor-dev/blob/729f399e10bdf94204e4bad8a439ac5c5263780e/core/plugindefinition.js#L183-L187
What should I add?

I followed localization style for `lang` property. I can change it to file system tree structure.

**Comment by jacekbogdanski** [comment]
After a second look, I see that

>These files are stored inside the `icons` directory in the plugin directory, follow the name pattern of `name.png`.

should be enough to describe the localization icon files, especially that we already have guide links inside [pluginDefinition](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_pluginDefinition.html) docs describing plugin structure thoroughly.

Although, sentence
> The list of icons available for this plugin.

is not accurate, because icons are registered by [`addIcon`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_skin.html#method-addIcon) method. It's the reason why they are available for [UI buttons](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_ui_button.html), despite that [`addButton`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog_definitionObject.html#method-addButton) method has no direct reference to the plugin.

**Comment by rafalk342** [comment]
> Although, sentence
> 
> > The list of icons available for this plugin.
> 
> is not accurate, because icons are registered by [`addIcon`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_skin.html#method-addIcon) method. It's the reason why they are available for [UI buttons](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_ui_button.html), despite that [`addButton`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog_definitionObject.html#method-addButton) method has no direct reference to the plugin.

I think that those icons actually are available for this plugin. Take a look at this code here https://github.com/ckeditor/ckeditor-dev/blob/c6969047a007e10d9bb2907ba11d0f25de1295d9/core/plugins.js#L38-L49
I see know that the usage I provided is a little bit wrong because *.png* is added automatically.

What other wording do you suggest?

**Comment by rafalk342** [comment]
> Actually, I find out that you set `major` branch as a target for your changes. It's only docs updates, so they should be merged into `master` branch. Could you rebase your branch into `master`, so we can merge your PR into the correct upstream branch without conflicts?

I has issues rebasing with the master. Instead I merged the current master with the branch. Is it ok?

**Comment by Dumluregn** [comment]
I added the reference about this PR closing #1709. #2947 was in fact its duplicate.

**Pull request merged**
